config/routes.rb
Rails.application.routes.draw do
  resources :purchase, only: [:index, :show] do
    collection do
      post 'pay', to: 'purchase#pay'
    end
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  resources :smses, only: :new

  resources :addresses, only: [:new, :edit, :update]

  resources :payments, only: [:new, :show] do
    collection do
      post 'pay', to: 'payments#pay'
    end
  end

  resources :closes, only: :new

  resources :product_images, only: :destroy

  resources :users, only: [:new, :index, :show, :edit, :destroy]

  resources :profiles, only: [:index, :show, :edit] do
    collection do
      get 'edit_address'
    end
  end


  resources :cards, only: [:index, :new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'buy'
      get 'search'
    end
  end

  resources :productitems, only: [:show]

  root 'products#index'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  validates :nickname, presence: true, length: { maximum: 20 }
  has_many :buyed_products, foreign_key: "buyer_id", class_name: "Product"
  has_many :selling_products, -> { where("buyer_id is NULL") }, foreign_key: "seller_id", class_name: "Product"
  has_many :sold_products, -> { where("buyer_id is not NULL") }, foreign_key: "seller_id", class_name: "Product"

  VALID_NAMEKANZI_REGEX = /\A[一-龥]+\z/
  validates :firstname, format: { with: VALID_NAMEKANZI_REGEX }
  validates :lastname, format: { with: VALID_NAMEKANZI_REGEX }
  VALID_NAMEKANA_REGEX = /\A[ァ-ヶー－]+\z/
  validates :firstname_kana, format: { with: VALID_NAMEKANA_REGEX }
  validates :lastname_kana, format: { with: VALID_NAMEKANA_REGEX }

  # # 空ではないこと
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :firstname_kana, presence: true
  validates :lastname_kana, presence: true
  # validates :birthday, presence: true

  # 都道府県
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  has_many :sns_credentials, dependent: :destroy

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first

    if snscredential.present? #sns登録のみ完了してるユーザー
      user = User.where(id: snscredential.user_id).first
      unless user.present? #ユーザーが存在しないなら
        user = User.new(
          # snsの情報
          nickname: auth.info.name,
          email: auth.info.email
        )
      end
      sns = snscredential

    else #sns登録 未
      user = User.where(email: auth.info.email).first
      if user.present? #会員登録 済
        sns = SnsCredential.new(
          uid: uid,
          provider: provider,
          user_id: user.id
        )
      else #会員登録 未
        user = User.new(
          nickname: auth.info.name,
          email: auth.info.email
        )
        sns = SnsCredential.create(
          uid: uid,
          provider: provider
        )
      end
    end
    # hashでsnsのidを返り値として保持しておく
    return { user: user , sns_id: sns.id }
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  # facebook認証用
  def facebook
    callback_for(:facebook) #コールバック
  end

  def google_oauth2
    callback_for(:google)
  end


  def callback_for(provider)
    info = User.find_oauth(request.env["omniauth.auth"]) #usersモデルのメソッド
    @user = info[:user]
    sns_id = info[:sns_id]
    # binding.pry
    if @user.persisted? #userが存在したら
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else #userが存在しなかったら
      session["devise.sns_id"] = sns_id #sns_credentialのid devise.他のアクションに持ち越せる(少し難)
      render template: "devise/registrations/new" #redirect_to だと更新してしまうのでrenderで
    end
  end

  def failure
    redirect_to root_path and return
  end

end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    new_smse_path
  end

  def after_sign_up_path_for(resource)
    new_smse_path
  end

  def create
    #binding.pry
    if params[:user][:password] == "" #sns登録なら
      params[:user][:password] = "Devise.friendly_token.first(6)" #deviseのパスワード自動生成機能を使用
      params[:user][:password_confirmation] = "Devise.friendly_token.first(6)"
      super
      # binding.pry
      sns = SnsCredential.update(user_id: @user.id)
    else #email登録なら
      # binding.pry
      super
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def destroy
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_l-side.html.haml
.l-side
  %nav.mypage-nav
    %ul.mypage-nav__list
      %li        
        = link_to "/users/new/", class: "mypage-nav-list-item" do
          マイページ
          %i.fas.fa-chevron-right
      %li
        = link_to "/#mypage-notification", class: "mypage-nav-list-item" do
          お知らせ
          %i.fas.fa-chevron-right
      %li
        = link_to "/#mypage-todo", class: "mypage-nav-list-item" do
          やることリスト
          %i.fas.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav-list-item" do
          いいね！一覧
          %i.fas.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav-list-item" do
          出品する
          %i.fas.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav-list-item" do
          出品した商品 - 出品中
          %i.fas.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav-list-item" do
          出品した商品 - 取引中
          %i.fas.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav-list-item" do
          出品した商品 - 売却済み
          %i.fas.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav-list-item" do
          購入した商品 - 取引中
          %i.fas.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav-list-item" do
          購入した商品 - 過去の取引
          %i.fas.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav-list-item" do
          ニュース一覧
          %i.fas.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav-list-item" do
          評価一覧
          %i.fas.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav-list-item" do
          ガイド
          %i.fas.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav-list-item" do
          お問い合わせ
          %i.fas.fa-chevron-right
    %h3.mypage-nav-head メルペイ
    %ul.mypage-nav__list
      %li
        = link_to "", class: "mypage-nav-list-item" do
          売上・振込申請
          %i.fas.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav-list-item" do
          ポイント
          %i.fas.fa-chevron-right
    %h3.mypage-nav-head 設定
    %ul.mypage-nav__list
      %li
        = link_to "", class: "mypage-nav-list-item" do
          プロフィール
          %i.fas.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav-list-item" do
          発送元・お届け先住所変更
          %i.fas.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav-list-item" do
          支払い方法
          %i.fas.fa-chevron-right
        = link_to "", class: "mypage-nav-list-item" do
          メール/パスワード
          %i.fas.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav-list-item" do
          本人情報
          %i.fas.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav-list-item" do
          電話番号の確認
          %i.fas.fa-chevron-right
      %li
        = link_to "", class: "mypage-nav-list-item" do
          ログアウト
          %i.fas.fa-chevron-right

app/views/users/address.html.haml
%body
  .user-signup

    .signup-wrapper

      %header.signup-header

        %h1

          = link_to new_user_registration_path do
            = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3160895340', alt: 'mercari', height: '', width: '', class: 'signup-header-img'

        %nav.progress-ber

          %ol.clearfix
            %li
              会員情報
              .progress-status.back-active
                .after.back-active
            %li
              電話番号認証
              .progress-status.back-active
                .before.back-active
                .after.back-active
            %li.active
              お届け先住所入力
              .progress-status.back-active
                .before.back-active
                .after
            %li
              支払い方法
              .progress-status
                .before
                .after
            %li
              完了
              .progress-status
                .before


      %main.signup-main

        %section.signup-main__container

          %h2.signup-head 住所入力

          .signup-inner

            = form_with(local: true) do |f|
              .form

                .form__group#first
                  = f.label :郵便番号
                  %span.form__group--require 必須
                  = f.number_field :postalcode, autofocus: true, autocomplete: "off", class: 'field-input', placeholder: "例）123-4567"

                .form__group
                  = f.label :都道府県
                  %span.form__g.form__group--require 必須
                  %br/

                  .birthday-select-wrap

                    .select-wrap#pref_name
                      %select.select-default
                        %option{:value => "北海道"} 北海道
                        %option{:value => "青森県"} 青森県
                        %option{:value => "岩手県"} 岩手県
                        %option{:value => "宮城県"} 宮城県
                        %option{:value => "秋田県"} 秋田県
                        %option{:value => "山形県"} 山形県
                        %option{:value => "福島県"} 福島県
                        %option{:value => "茨城県"} 茨城県
                        %option{:value => "栃木県"} 栃木県
                        %option{:value => "群馬県"} 群馬県
                        %option{:value => "埼玉県"} 埼玉県
                        %option{:value => "千葉県"} 千葉県
                        %option{:value => "東京都"} 東京都
                        %option{:value => "神奈川県"} 神奈川県
                        %option{:value => "新潟県"} 新潟県
                        %option{:value => "富山県"} 富山県
                        %option{:value => "石川県"} 石川県
                        %option{:value => "福井県"} 福井県
                        %option{:value => "山梨県"} 山梨県
                        %option{:value => "長野県"} 長野県
                        %option{:value => "岐阜県"} 岐阜県
                        %option{:value => "静岡県"} 静岡県
                        %option{:value => "愛知県"} 愛知県
                        %option{:value => "三重県"} 三重県
                        %option{:value => "滋賀県"} 滋賀県
                        %option{:value => "京都府"} 京都府
                        %option{:value => "大阪府"} 大阪府
                        %option{:value => "兵庫県"} 兵庫県
                        %option{:value => "奈良県"} 奈良県
                        %option{:value => "和歌山県"} 和歌山県
                        %option{:value => "鳥取県"} 鳥取県
                        %option{:value => "島根県"} 島根県
                        %option{:value => "岡山県"} 岡山県
                        %option{:value => "広島県"} 広島県
                        %option{:value => "山口県"} 山口県
                        %option{:value => "徳島県"} 徳島県
                        %option{:value => "香川県"} 香川県
                        %option{:value => "愛媛県"} 愛媛県
                        %option{:value => "高知県"} 高知県
                        %option{:value => "福岡県"} 福岡県
                        %option{:value => "佐賀県"} 佐賀県
                        %option{:value => "長崎県"} 長崎県
                        %option{:value => "熊本県"} 熊本県
                        %option{:value => "大分県"} 大分県
                        %option{:value => "宮崎県"} 宮崎県
                        %option{:value => "鹿児島県"} 鹿児島県
                        %option{:value => "沖縄県"} 沖縄県


                .form__group
                  = f.label :市区町村
                  %span.form__group--require 必須
                  = f.text_field :city_name, autofocus: true, autocomplete: "off", class: 'field-input', placeholder: "例）横浜市緑区"

                .form__group
                  = f.label :番地
                  %span.form__group--require 必須
                  = f.text_field :address_number, autofocus: true, autocomplete: "off", class: 'field-input', placeholder: "例）青山1-1-1"

                .form__group
                  = f.label :建物名
                  %span.form__group--voluntary 任意
                  = f.text_field :building_name, autofocus: true, autocomplete: "off", class: 'field-input', placeholder: "例）柳ビル103"

                .form__group
                  = f.label :電話
                  %span.form__group--voluntary 任意
                  = f.number_field :phone_number, autofocus: true, autocomplete: "off", class: 'field-input', placeholder: "09012345678"

                = f.submit "次へ進む", class: 'btn-red btn-befault'

                = link_to "次へ進む(仮)" ,users_registration_payment_path, class: "btn-red btn-befault"

                %p.info-text
                  ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。

                .form__group
                  %p.text-right.rink-bule
                    = link_to new_user_registration_path, class: "link-blue" do
                      電話番号の確認が必要な理由
                      %i.fas.fa-angle-right

      = render partial: 'footer'

app/views/users/close.html.haml
%body
  .user-signup

    .signup-wrapper

      %header.signup-header

        %h1

          = link_to new_user_registration_path do
            = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3160895340', alt: 'mercari', height: '', width: '', class: 'signup-header-img'

        %nav.progress-ber

          %ol.clearfix
            %li
              会員情報
              .progress-status.back-active
                .after.back-active
            %li
              電話番号認証
              .progress-status.back-active
                .before.back-active
                .after.back-active
            %li
              お届け先住所入力
              .progress-status.back-active
                .before.back-active
                .after.back-active
            %li
              支払い方法
              .progress-status.back-active
                .before.back-active
                .after.back-active
            %li.active
              完了
              .progress-status.back-active
                .before.back-active


      %main.signup-main

        %section.signup-main__container

          %h2.signup-head 会員登録完了

          .signup-inner

            .form

              .form__group#first

              .form__group
                %p.text-center#close
                  ありがとうございます。
                %p.text-center#close
                  会員登録が完了しました。

              = link_to "メルカリをはじめる" ,new_user_registration_path, class: "btn-red btn-befault"

      = render partial: 'footer'

app/views/users/index.html.haml
= render "layouts/header"

.user-logout
  .content
    .chapter
      .inner
        .logout
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn-default btn-red" ,style: "text-decoration: none;"

  = render 'layouts/l-side'

= render 'layouts/aside'

= render 'layouts/footer'

app/views/users/new.html.haml
%body
  .user-new
    .signup-wrapper
      %header.signup-header
        %h1
          = link_to root_path do
            = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3160895340', alt: 'mercari', height: '', width: '', class: 'signup-header-img'

      .signup-main
        .signup-panel
          %h2 新規会員登録
          .signup-inner
            .signin-mail
            .login-sns
              = link_to new_user_registration_path do
                %button.btn-default.btn-sns.btn-mail
                  メールアドレスで登録
                  .i.far.fa-envelope.fa-2x
              = link_to user_facebook_omniauth_authorize_path do
                %button.btn-default.btn-sns.btn-sns-facebook
                  Facebookで登録
                  .i.fab.fa-facebook-square.fa-2x
              = link_to user_google_oauth2_omniauth_authorize_path do
                %button.btn-default.btn-sns.btn-sns-google
                  Googleで登録
                  .i.fab.fa-google.fa-2x

      = render 'layouts/signup-footer'

app/views/users/payment.html.haml
%body
  .user-signup

    .signup-wrapper

      %header.signup-header

        %h1

          = link_to new_user_registration_path do
            = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3160895340', alt: 'mercari', height: '', width: '', class: 'signup-header-img'

        %nav.progress-ber

          %ol.clearfix
            %li
              会員情報
              .progress-status.back-active
                .after.back-active
            %li
              電話番号認証
              .progress-status.back-active
                .before.back-active
                .after.back-active
            %li
              お届け先住所入力
              .progress-status.back-active
                .before.back-active
                .after.back-active
            %li.active
              支払い方法
              .progress-status.back-active
                .before.back-active
                .after
            %li
              完了
              .progress-status
                .before


      %main.signup-main

        %section.signup-main__container

          %h2.signup-head 支払い方法

          .signup-inner

            = form_with(local: true) do |f|
              .form

                .form__roup#first

                .form__group

                = link_to "次へ進む(仮)" ,users_registration_close_path, class: "btn-red btn-befault"

      = render partial: 'footer'

app/views/users/sms.html.haml
%body
  .user-signup

    .signup-wrapper

      %header.signup-header

        %h1

          = link_to new_user_registration_path do
            = image_tag '//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3160895340', alt: 'mercari', height: '', width: '', class: 'signup-header-img'

        %nav.progress-ber

          %ol.clearfix
            %li
              会員情報
              .progress-status.back-active
                .after.back-active
            %li.active
              電話番号認証
              .progress-status.back-active
                .before.back-active
                .after
            %li
              お届け先住所入力
              .progress-status
                .before
                .after
            %li
              支払い方法
              .progress-status
                .before
                .after
            %li
              完了
              .progress-status
                .before


      %main.signup-main

        %section.signup-main__container

          %h2.signup-head 電話番号の確認

          .signup-inner

            = form_with(local: true) do |f|
              .form

                .form__group#first
                  = f.label :携帯電話の番号
                  = f.number_field :phone_number, autofocus: true, autocomplete: "off", class: 'field-input', placeholder: "携帯電話の番号を入力"

                %p.info-text#black
                  ※本人確認のため、携帯電話のSNS(ショートメッセージサービス)を利用して認証を行います。

                = f.submit "次へ進む", class: 'btn-red btn-befault'

                = link_to "次へ進む(仮)" ,users_registration_address_path, class: "btn-red btn-befault"

                %p.info-text
                  ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。

                .form__group
                  %p.text-right.rink-bule
                    = link_to new_user_registration_path, class: "link-blue" do
                      電話番号の確認が必要な理由
                      %i.fas.fa-angle-right

      = render partial: 'footer'