config/routes.rb
Rails.application.routes.draw do
  resources :purchase, only: [:index, :show] do
    collection do
      post 'pay', to: 'purchase#pay'
    end
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  resources :smses, only: :new

  resources :addresses, only: [:new, :edit, :update]

  resources :payments, only: [:new, :show] do
    collection do
      post 'pay', to: 'payments#pay'
    end
  end

  resources :closes, only: :new

  resources :product_images, only: :destroy

  resources :users, only: [:new, :index, :show, :edit, :destroy]

  resources :profiles, only: [:index, :show, :edit] do
    collection do
      get 'edit_address'
    end
  end


  resources :cards, only: [:index, :new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'buy'
      get 'search'
    end
  end

  resources :productitems, only: [:show]

  root 'products#index'

end

app/controllers/productitems_controller.rb
class ProductitemsController < ApplicationController

  def show
    @product = Product.find(params[:id])
    @products = Product.where(category_id: @product.category_id)
  end

end

app/views/productitems/show.html.haml
.wrapper-product-destroy
  = render 'layouts/header'
  - if flash[:notice]
    .flash-message
      .flash-message__text
        = flash[:notice]
  %h1.destroy-head 商品編集削除
  .show-products
    .product-contents
      %h1
        = @product.name
      .product-contents__main-content
        .product-contents__main-content--photos-flame
          .gallery
            - if @product.images.attached?
              - @product.images.each_with_index do |image, i|
                = image_tag image, class:"photo photo-#{i}"
          .owl-dots
            - if @product.images.attached?
              - @product.images.each_with_index do |image, i|
                .owl-dot
                  = image_tag image, class:"photo photo-#{i}"
        %table.product-contents__main-content--table{:cellspacing => "0"}
          %tr
            %th.border-top 出品者
            %td.border-top
              = @product.seller.nickname
          %tr
            %th カテゴリー
            %td
              - if @product.category.present?
                .name
                = @product.category.name
          %tr
            %th ブランド
            %td
              - if @product.bland.present?
                = @product.bland
          %tr
            %th 商品の状態
            %td
              = @product.condition
          %tr
            %th 商品のサイズ
            %td
              - if @product.size.present?
                = @product.size
          %tr
            %th 配送料の負担
            %td
              = @product.shipping_cost
          %tr
            %th 配送の方法
            %td
              = @product.shipping_method
          %tr
            %th 配送元地域
            %td
              = @product.source_area
          %tr
            %th 発送日の目安
            %td
              = @product.shipping_day
      .product-contents__price-box
        .product-contents__price-box--number
          .product-price-destroy
            ¥
            = @product.price
          .product-tax
            (税込)
          .product-shipping-fee
            送料込み

.container
  .content
    .destroy-main
      %h2.destroy-head
      .setting-destroy
        = link_to "商品の編集", edit_product_path, method: :GET, class: "btn-edit-red"
        %p or
        = link_to "出品を一旦停止する", "", data: { confirm: "現在、対応処理が出来ませんません。"}, class: "btn-delete-gray"
        = link_to "この商品を削除する", product_path(@product), method: :delete, data: { confirm: "この商品を削除します。本当によろしいですか？"}, class: "btn-delete-gray"

= render 'layouts/aside'
= render 'layouts/footer'