config/routes.rb
Rails.application.routes.draw do
  resources :purchase, only: [:index, :show] do
    collection do
      post 'pay', to: 'purchase#pay'
    end
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  resources :smses, only: :new

  resources :addresses, only: [:new, :edit, :update]

  resources :payments, only: [:new, :show] do
    collection do
      post 'pay', to: 'payments#pay'
    end
  end

  resources :closes, only: :new

  resources :product_images, only: :destroy

  resources :users, only: [:new, :index, :show, :edit, :destroy]

  resources :profiles, only: [:index, :show, :edit] do
    collection do
      get 'edit_address'
    end
  end


  resources :cards, only: [:index, :new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'buy'
      get 'search'
    end
  end

  resources :productitems, only: [:show]

  root 'products#index'

end

app/models/card.rb
class Card < ApplicationRecord
  validates :user_id, presence: true
  validates :customer_id, presence: true
  validates :card_id, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"

  def index
    card = Card.where(user_id: current_user)
    redirect_to action: "show" if card.exists?
  end

  def new
    card = Card.where(user_id: current_user)
    redirect_to action: "show" if card.exists?
  end

  def pay
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params["payjp_token"].blank?
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(card: params["payjp_token"])
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "pay"
      end
    end
  end

  def delete
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "index"
  end

  def show
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "index"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.haml
.new-card-main
  .new-card-main__content
    .content__area
      %h2.content__area__head 支払い方法
      = form_with(url: pay_payments_path, local: true, method: :post, id: 'charge-form', class: 'content__area__info') do |f|
        .form
          .form__group
            = f.label :カード番号
            %span.form__require 必須
            = f.text_field :number,  class: "input__default", placeholder: "半角数字のみ" , maxlength: "16", type: "text", id: "card__number"
            %ul.sign-up__card__list
              %li
                = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?2399382397', width: '49', height: '20'
              %li
                = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?2399382397', width: '34', height: '20'
              %li
                = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?2399382397', width: '30', height: '20'
              %li
                = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?2399382397', width: '32', height: '20'
              %li
                = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?2399382397', width: '21', height: '20'
              %li
                = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?2399382397', width: '32', height: '20'
              %li
                = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?2399382397', width: '32', height: '20'
          .form__group.signup__from-expire
            = f.label :有効期限
            %span.form__require 必須
            .select__wrapdd
              %select#exp_month{name: "exp_month", type: "text"}
                %option{value: "1"}01
                %option{value: "2"}02
                %option{value: "3"}03
                %option{value: "4"}04
                %option{value: "5"}05
                %option{value: "6"}06
                %option{value: "7"}07
                %option{value: "8"}08
                %option{value: "9"}09
                %option{value: "10"}10
                %option{value: "11"}11
                %option{value: "12"}12
              %i.fas.fa-chevron-down
              %span.form__month 月
            .select__wrapdd
              %select#exp_year{name: "exp_year", type: "text"}
                %option{value: "2019"}19
                %option{value: "2020"}20
                %option{value: "2021"}21
                %option{value: "2022"}22
                %option{value: "2023"}23
                %option{value: "2024"}24
                %option{value: "2025"}25
                %option{value: "2026"}26
                %option{value: "2027"}27
                %option{value: "2028"}28
                %option{value: "2029"}29
              %i.fas.fa-chevron-down
              %span.form__month 年
          .form__group
            = f.label :セキュリティコード
            %span.form__require 必須
            = f.text_field :cvc, type: "text", placeholder: "カード背面４桁もしくは３桁の番号", class: "cvc", maxlength: "4", id: "cvc"
            .signup__seqcode
              .signup__seqcode__text
                %span.form__question ?
                カード裏面の番号とは？
          = f.submit "次へ進む", id: "token_submit", class: "btn__default btn--red", url: new_close_path #, class: "none"
          -# = link_to "次へ進む" ,new_close_path, class: "btn__default btn--red"

app/views/cards/index.html.haml
.card_registration
  - breadcrumb :index_card
  = render 'layouts/header'
  .main
    .main__content
      .content__area
        %h2.content__area__head 支払い方法
        .content__area__inner
          .inner__area
            .inner__area__head
              %h3.inner__head__text クレジットカード一覧
          .add-card
            .add-card__area
              = link_to new_card_path, class: "add-card__area__text" do
                %i.far.fa-credit-card
                クレジットカードを追加する
          .how-regist
            %a.how-regist__area
              %span.how-regist__area__te
    = render 'layouts/l-side'
  = render 'layouts/aside'
  = render 'layouts/footer'

app/views/cards/new.html.haml
.card_registration
  - breadcrumb :new_card
  = render 'layouts/header'
  .main
    .main__content
      .content__area
        %h2.content__area__head クレジットカード情報入力
        = form_with(url: pay_cards_path, local: true, method: :post, id: 'charge-form', class: 'content__area__info') do |f|
          .form
            .form__group
              = f.label :カード番号
              %span.form__require 必須
              = f.text_field :number,  class: "input__default", placeholder: "半角数字のみ" , maxlength: "16", type: "text", id: "card__number"
              %ul.sign-up__card__list
                %li
                  = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?2399382397', width: '49', height: '20'
                %li
                  = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/master-card.svg?2399382397', width: '34', height: '20'
                %li
                  = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/saison-card.svg?2399382397', width: '30', height: '20'
                %li
                  = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/jcb.svg?2399382397', width: '32', height: '20'
                %li
                  = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/american_express.svg?2399382397', width: '21', height: '20'
                %li
                  = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/dinersclub.svg?2399382397', width: '32', height: '20'
                %li
                  = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/discover.svg?2399382397', width: '32', height: '20'
            .form__group.signup__from-expire
              = f.label :有効期限
              %span.form__require 必須
              .select__wrapdd
                %select#exp_month{name: "exp_month", type: "text"}
                  %option{value: "1"}01
                  %option{value: "2"}02
                  %option{value: "3"}03
                  %option{value: "4"}04
                  %option{value: "5"}05
                  %option{value: "6"}06
                  %option{value: "7"}07
                  %option{value: "8"}08
                  %option{value: "9"}09
                  %option{value: "10"}10
                  %option{value: "11"}11
                  %option{value: "12"}12
                %i.fas.fa-chevron-down
                %span.form__month 月
              .select__wrapdd
                %select#exp_year{name: "exp_year", type: "text"}
                  %option{value: "2019"}19
                  %option{value: "2020"}20
                  %option{value: "2021"}21
                  %option{value: "2022"}22
                  %option{value: "2023"}23
                  %option{value: "2024"}24
                  %option{value: "2025"}25
                  %option{value: "2026"}26
                  %option{value: "2027"}27
                  %option{value: "2028"}28
                  %option{value: "2029"}29
                %i.fas.fa-chevron-down
                %span.form__month 年
            .form__group
              = f.label :セキュリティコード
              %span.form__require 必須
              = f.text_field :cvc, type: "text", placeholder: "カード背面４桁もしくは３桁の番号", class: "cvc", maxlength: "4", id: "cvc"
              .signup__seqcode
                .signup__seqcode__text
                  %span.form__question ?
                  カード裏面の番号とは？
            = f.submit "追加する", id: "token_submit", class: "btn__default btn--red"
    = render 'layouts/l-side'
  = render 'layouts/aside'
  = render 'layouts/footer'

app/views/cards/show.html.haml
.card_registration
  - breadcrumb :show_card
  = render 'layouts/header'
  .main
    .main__content
      .content__area
        %h2.content__area__head 支払い方法
        .content__area__inner
          .inner__area
            .inner__area__head
              %h3.inner__head__text クレジットカード一覧
          .payment__list
            %ul.payment__list__area
              %li
                = image_tag '//www-mercari-jp.akamaized.net/assets/img/card/visa.svg?2399382397', width: '49', height: '20'
              .credit__num
                = "**** **** **** " + @default_card_information.last4
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              .credit__year__month
                = exp_month + " / " + exp_year
              = form_with(url: delete_cards_path, local: true, method: :post, id: 'charge-form',  name: "inputForm") do |f|
                = f.text_field :card_id, type: "hidden"
                = f.submit "削除する", class: "payment__remove"
          .how-regist
            %a.how-regist__area
              %span.how-regist__area__text 支払い方法について
              %i.fas.fa-chevron-right
    = render 'layouts/l-side'
  = render 'layouts/aside'
  = render 'layouts/footer'