config/routes.rb
Rails.application.routes.draw do
  resources :purchase, only: [:index, :show] do
    collection do
      post 'pay', to: 'purchase#pay'
    end
  end
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  resources :smses, only: :new

  resources :addresses, only: [:new, :edit, :update]

  resources :payments, only: [:new, :show] do
    collection do
      post 'pay', to: 'payments#pay'
    end
  end

  resources :closes, only: :new

  resources :product_images, only: :destroy

  resources :users, only: [:new, :index, :show, :edit, :destroy]

  resources :profiles, only: [:index, :show, :edit] do
    collection do
      get 'edit_address'
    end
  end


  resources :cards, only: [:index, :new, :show] do
    collection do
      post 'show', to: 'cards#show'
      post 'pay', to: 'cards#pay'
      post 'delete', to: 'cards#delete'
    end
  end

  resources :products, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    collection do
      get 'buy'
      get 'search'
    end
  end

  resources :productitems, only: [:show]

  root 'products#index'

end

app/models/product.rb
class Product < ApplicationRecord
  has_many_attached :images
  belongs_to :buyer, class_name: "User", optional: true
  belongs_to :seller, class_name: "User"
  belongs_to :category

  enum condition:       { 新品、未使用: 0, 未使用に近い: 1, 目立った傷や汚れなし: 2, やや傷や汚れあり: 3, 傷や汚れあり: 4, 全体的に状態が悪い: 5}
  enum shipping_cost:   { "送料込み(出品者負担)": 0, "着払い(購入者負担)": 1 }
  enum source_area:     { 北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
                          茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
                          新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
                          岐阜県:21,静岡県:22,愛知県:23,三重県:24,
                          滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
                          鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
                          徳島県:36,香川県:37,愛媛県:38,高知県:39,
                          福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,沖縄県:47,
                          未定:48
                        }
  enum shipping_day:    { "1〜2日で発送": 0, "2〜3日で発送": 1, "4〜7日で発送": 2}
  enum shipping_method: { "らくらくメルカリ便": 1, "ゆうメール": 2, "レターパック": 3, "普通郵便(定形、定形外)": 4, "クロネコヤマト": 5, "ゆうパック": 6, "クリックポスト": 7, "ゆうパケット": 8}
  enum status:          { 出品中: 0, 取引中: 1, 購入済み: 2 }
  enum size:            { "XXS以下": 0, "XS(SS)": 1, "S": 2, "M": 3, "L": 4, "XL(LL)": 5, "2XL(3L)": 6, "3XL(4L)": 7, "4XL(5L)以上": 8, "FREE SIZE": 9}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def new
    @product = Product.new
    @parent = Category.order("id ASC").limit(13)
  end

  def index

    @ladies = Category.bring(1)
    @mens = Category.bring(2)
    @kids = Category.bring(3)
    @cosmetics = Category.bring(7)

    @chanels = Product.where(bland: "CHANEL").reject{|e| e[:buyer_id] != nil}
    @vuittons = Product.where(bland: "LOUIS VUITTON").reject{|e| e[:buyer_id] != nil}
    @supremes = Product.where(bland: "Supreme").reject{|e| e[:buyer_id] != nil}
    @nikes = Product.where(bland: "NIKE").reject{|e| e[:buyer_id] != nil}
  end

  def search
    if params[:cat]
      @categories = Category.find(params[:cat]).children
    else
      @childCategories = Category.find(params[:childCat]).children
    end
  end

  def show
    category_id = @product.category_id
    @products = Category.find(category_id).products.reject{|e| e[:buyer_id] != nil}
  end

  def create
    @product = Product.create(product_params)
    redirect_to products_path
  end

  def edit
    @parent = Category.order("id ASC").limit(13)
  end

  def update
    @product.update(product_params)
    redirect_to products_path
  end


  def destroy
    if @product.destroy
      redirect_to root_path
    else
      flash[:notice] = "削除に失敗しました。"
      redirect_to productitem_path(@product)
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :category_id, :condition, :size, :bland, :shipping_cost, :shipping_method, :source_area, :shipping_day, :status, :buyer_id, :price, images: []).merge(seller_id: current_user.id)
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product-list.html.haml
.main__list__item-box
  - if products.present?
    -  products.last(4).reverse_each do |product|
      .item-boxs
        = link_to("products/#{product.id}") do
          %figure
            - if product.images.attached?
              - product.images.each_with_index do |image, i|
                - if i == 0
                  = image_tag image, class:"img"
          .item-boxs__body
            %h3.item-boxs__name
              = product.name
            .item-boxs__num
              .item-boxs__price
                = product.price
            %p.tax (税込)

app/views/products/_sub-footer.html.haml
%footer.sub-footer
  %nav
    %ul.policy
      %li プライバシーポリシー
      %li メルカリ利用規約
      %li 特定商取引に関する表記
  = link_to class: 'single-footer-logo' do
    = image_tag( "//www-mercari-jp.akamaized.net/assets/img/common/common/logo-gray.svg?3856598694", width: "80", height: "65")
  %p.copyright
    © 2019 Mercari

app/views/products/create.html.haml
= link_to "商品出品ページ", new_product_path

app/views/products/edit.html.haml
.new-product
  .new-product__header
    .single-header
      =link_to "/" do
        = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3856598694", alt: "mercari"
  .new-product__main
  = form_with model: @product, local: true do |f|
    .new-product__main__contents
      .new-product__main__contents__head
        %h 商品の情報を入力
      .sell-form__image
        .sell-form__image__field
          %label
            出品画像
            %span 必須
        .sell-form__image__text 最大10枚までアップロードできます
        - if @product.images.length == 0
          #image_field
            = f.label :images, for: "upload_field" do
              .upload_field__text
                ドラッグアンドドロップ
                %br
                またはクリックしてファイルをアップロード
              = f.file_field :images, class: "sell-form__image__upload", multiple: true, style: "display: none", id: "upload_field"
            .preview
        - else
          #image_field_edit
            = f.label :images, for: "upload_field" do
              .upload_field__text
                ドラッグアンドドロップ
                %br
                またはクリックしてファイルをアップロード
            .preview
              - @product.images.each do |image|
                = image_tag image.variant(resize: "116x116"), class: "preview__image"
                .preview__btn
                  = link_to "削除", product_image_path, method: :delete, class: "preview__btn__delete"
                  = link_to "編集", "", class: "preview__btn__edit"
              = f.file_field :images, class: "sell-form__image__upload", multiple: true, style: "display: none", id: "upload_field"
    .new-product__sell-form
      .sell-form__container
        .sell-form__container__name
          %label
            商品名
            %span 必須
          = f.text_field :name, class: "sell-form__container__name__title", placeholder: "商品名（必須 40文字まで)"
        .sell-form__container__description
          %label
            商品の説明
            %span 必須
          = f.text_area :description, class: "sell-form__container__description__form", rows: "5", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
      .sell-form__detail
        .sell-form__detail__name
          %h3 商品の詳細
          .sell-form__detail__select-box
            .sell-form__detail__select-box__category
              %label
                カテゴリー
                %span 必須
              %select#product_category_id
                %option= @product.category.root.name
                - @parent.each do |category|
                  %option{ id: category.id}= category.name
              %select#select_id
                %option 
                  = @product.category.parent.name
              %select#child_id
                %option 
                  = @product.category.name
            .sell-form__detail__select-box__size
              %label
                サイズ
                %span 必須
              .sell-form__size
                = f.select :size, Product.sizes.keys, prompt: "---"
            .sell-form__detail__select-box__bland
              %label
                ブランド
                %span 任意
              .bland-serect 
                = f.select :bland, ['',  'CHANEL', 'LOUIS VUITTON', 'Supreme', 'NIKE']
            .sell-form__detail__select-box__condition
              %label 
                商品の状態
                %span 必須
              .sell-form__condition
                = f.select :condition, Product.conditions.keys, prompt: "---"
      .sell-form__shipping
        .sell-form__shipping__name
          %h3
            配送について
            = link_to "?", "/", class: "help"
          .sell-form__shipping__select-box
            .sell-form__shipping__select-box__fee
              %label
                配送料の負担
                %span 必須
              .sell-form__fee
                = f.select :shipping_cost, Product.shipping_costs.keys, prompt: "---"
            .sell-form__shipping__select-box__method
              %label
                配送の方法
                %span 必須
              .sell-form__method
                = f.select :shipping_method, Product.shipping_methods.keys, prompt: "---"
            .sell-form__shipping__select-box__area
              %label
                発送元の地域
                %span 必須
              .sell-form__area
                = f.select :source_area, Product.source_areas.keys, prompt: "---"
            .sell-form__shipping__select-box__day
              %label
                発送までの日数
                %span 必須
              .sell-form__day
                = f.select :shipping_day, Product.shipping_days.keys, prompt: "---"
      .sell-form__price
        %h3
          販売価格(300〜9,999,999)
          = link_to "?", "/", class: "help"
        .sell-form__price__box
          .sell-form__price__box__input
            %label.sell-form__price__box__input__left
              価格
              %span 必須
            .sell-form__price__box__input__right
              %div
                = f.text_field :price, class: "input-price", placeholder: "例）300"
          .sell-form__price__box__charge
            .sell-form__price__box__charge__left
              %p 販売手数料 (10%)
            .sell-form__price__box__charge__right -
          .sell-form__price__box__profit
            .sell-form__price__box__profit__left
              %p 販売利益
            .sell-form__price__box__profit__right -
      .status-form{ hidden: "" }
        = f.select :status, Product.statuses.keys
      .buyer-form{ hidden: "" }
        = f.text_field :buyer_id
      .sell-form__submit
        %p 禁止されている出品、行為を必ずご確認ください。
        %p またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
        %p また、出品をもちまして加盟店規約に同意したことになります。
        .sell-form__submit__button
          = f.submit "変更する", class: "edit__btn", type: "submit"
        = link_to "もどる", "/", class: "sell-form__submit__back"

      = render "sub-footer"

app/views/products/index.html.haml
.toppage
  = render 'layouts/header'
  .main
    .main__list
      %h2.main__list__title ピックアップカテゴリー
      .main__list__item
        %h3.main__list__sub-title レディース 新着アイテム
        = render partial: 'product-list', locals: {products: @ladies}
        .view__all
          %a すべての商品を見る
      .main__list__item
        %h3.main__list__sub-title メンズ 新着アイテム
        = render partial: 'product-list', locals: {products: @mens}
        .view__all
          %a すべての商品を見る
      .main__list__item
        %h3.main__list__sub-title ベビー・キッズ 新着アイテム
        = render partial: 'product-list', locals: {products: @kids}
        .view__all
          %a すべての商品を見る
      .main__list__item
        %h3.main__list__sub-title コスメ・香水・美容 新着アイテム
        = render partial: 'product-list', locals: {products: @cosmetics}
        .view__all
          %a すべての商品を見る
    .main__list
      %h2.main__list__title ピックアップブランド
      .main__list__item
        %h3.main__list__sub-title シャネル 新着アイテム
        = render partial: 'product-list', locals: {products: @chanels}
        .view__all
          %a すべての商品を見る
      .main__list__item
        %h3.main__list__sub-title ルイ ヴィトン 新着アイテム
        = render partial: 'product-list', locals: {products: @vuittons}
        .view__all
          %a すべての商品を見る
      .main__list__item
        %h3.main__list__sub-title シュプリーム 新着アイテム
        = render partial: 'product-list', locals: {products: @supremes}
        .view__all
          %a すべての商品を見る
      .main__list__item
        %h3.main__list__sub-title ナイキ 新着アイテム
        = render partial: 'product-list', locals: {products: @nikes}
        .view__all
          %a すべての商品を見る
    .flame
      #gallery
        .easy-photo
          .easy__main__content
            .easy__main__area
              .area__content
                %h2.area__text スマホでかんたん
                %h2.area__text フリマアプリ
                %p.area__detail メルカリはスマホカメラからすぐに出品できる
                %p.area__detail 購入時も安心な独自システムのアプリです
                .vitual-store
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/app-store.svg?3856598694", class: "store-img"
                  = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/google-play.svg?3856598694", class: "store-img"
              = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/jp/top/main_content_pc.png?3856598694", class: "iphone-img"
        = image_tag "https://www.mercari.com/jp/assets/img/common/jp/top/banner-6th-thanks.jpg", class: "camp-photo"
        = image_tag "https://www.mercari.com/jp/assets/img/common/jp/top/banner-6th-thanks.jpg", class: "natukasi-photo"
      .nav
        #prev
        #next
      #dots
        .left-dot.dot
        .center-dot.dot
        .right-dot.dot
  = render 'layouts/aside'
  = render 'layouts/footer'
  =link_to "products/new" do
    .sell-btn
      .sell-btn__text 出品
      %i.fas.fa-camera

app/views/products/new.html.haml
.new-product
  .new-product__header
    .single-header
      =link_to "/" do
        = image_tag "//www-mercari-jp.akamaized.net/assets/img/common/common/logo.svg?3856598694", alt: "mercari"
  .new-product__main
  = form_with model: @product, local: true do |f|
    .new-product__main__contents
      .new-product__main__contents__head
        %h 商品の情報を入力
      .sell-form__image
        .sell-form__image__field
          %label
            出品画像
            %span 必須
        .sell-form__image__text 最大10枚までアップロードできます
        #image_field
          = f.label :images, for: "upload_field" do
            .upload_field__text
              ドラッグアンドドロップ
              %br
              またはクリックしてファイルをアップロード
            = f.file_field :images, class: "sell-form__image__upload", multiple: true, style: "display: none", id: "upload_field"
          .preview
    .new-product__sell-form
      .sell-form__container
        .sell-form__container__name
          %label
            商品名
            %span 必須
          = f.text_field :name, class: "sell-form__container__name__title", placeholder: "商品名（必須 40文字まで)"
        .sell-form__container__description
          %label
            商品の説明
            %span 必須
          = f.text_area :description, class: "sell-form__container__description__form", rows: "5", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。"
      .sell-form__detail
        .sell-form__detail__name
          %h3 商品の詳細
          .sell-form__detail__select-box
            .sell-form__detail__select-box__category
              %label
                カテゴリー
                %span 必須
              %select#product_category_id
                %option ---
                - @parent.each do |category|
                  %option{ id: category.id}= category.name
            .sell-form__detail__select-box__size
              %label
                サイズ
                %span 必須
              .sell-form__size
                = f.select :size, Product.sizes.keys, prompt: "---"
            .sell-form__detail__select-box__bland
              %label
                ブランド
                %span 任意
              .bland-serect 
                = f.select :bland, ['',  'CHANEL', 'LOUIS VUITTON', 'Supreme', 'NIKE']
            .sell-form__detail__select-box__condition
              %label 
                商品の状態
                %span 必須
              .sell-form__condition
                = f.select :condition, Product.conditions.keys, prompt: "---"
      .sell-form__shipping
        .sell-form__shipping__name
          %h3
            配送について
            = link_to "?", "/", class: "help"
          .sell-form__shipping__select-box
            .sell-form__shipping__select-box__fee
              %label
                配送料の負担
                %span 必須
              .sell-form__fee
                = f.select :shipping_cost, Product.shipping_costs.keys, prompt: "---"
            .sell-form__shipping__select-box__method
              %label
                配送の方法
                %span 必須
              .sell-form__method
                = f.select :shipping_method, Product.shipping_methods.keys, prompt: "---"
            .sell-form__shipping__select-box__area
              %label
                発送元の地域
                %span 必須
              .sell-form__area
                = f.select :source_area, Product.source_areas.keys, prompt: "---"
            .sell-form__shipping__select-box__day
              %label
                発送までの日数
                %span 必須
              .sell-form__day
                = f.select :shipping_day, Product.shipping_days.keys, prompt: "---"
      .sell-form__price
        %h3
          販売価格(300〜9,999,999)
          = link_to "?", "/", class: "help"
        .sell-form__price__box
          .sell-form__price__box__input
            %label.sell-form__price__box__input__left
              価格
              %span 必須
            .sell-form__price__box__input__right
              = f.text_field :price, class: "input-price", placeholder: "例）300"
          .sell-form__price__box__charge
            .sell-form__price__box__charge__left
              %p 販売手数料 (10%)
            .sell-form__price__box__charge__right -
          .sell-form__price__box__profit
            .sell-form__price__box__profit__left
              %p 販売利益
            .sell-form__price__box__profit__right -
      .status-form{ hidden: "" }
        = f.select :status, Product.statuses.keys
      .buyer-form{ hidden: "" }
        = f.text_field :buyer_id
      .sell-form__submit
        %p 禁止されている出品、行為を必ずご確認ください。
        %p またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
        %p また、出品をもちまして加盟店規約に同意したことになります。
        .sell-form__submit__button
          = f.submit "出品する", class: "sell-form__submit__button__btn", type: "submit"
        = link_to "もどる", "/", class: "sell-form__submit__back"

      = render "sub-footer"

app/views/products/show.html.haml
.wrapper-products
  - breadcrumb :show_product, @product
  = render 'layouts/header'
  .show-products
    .product-contents
      %h1
        = @product.name
      .product-contents__main-content
        .product-contents__main-content--photos-flame
          .gallery
            - if @product.images.attached?
              - @product.images.each_with_index do |image, i|
                = image_tag image, class:"photo photo-#{i}"
          .owl-dots
            - if @product.images.attached?
              - @product.images.each_with_index do |image, i|
                .owl-dot
                  = image_tag image, class:"photo photo-#{i}"
        %table.product-contents__main-content--table{:cellspacing => "0"}
          %tr
            %th.border-top 出品者
            %td.border-top
              = @product.seller.nickname
          %tr
            %th カテゴリー
            %td
              - if @product.category.present?
                .name
                = @product.category.root.name
                .name
                >
                = @product.category.parent.name
                .name
                >
                = @product.category.name
          %tr
            %th ブランド
            %td
              - if @product.bland.present?
                = @product.bland
          %tr
            %th 商品の状態
            %td
              = @product.condition
          %tr
            %th 商品のサイズ
            %td
              - if @product.size.present?
                = @product.size
          %tr
            %th 配送料の負担
            %td
              = @product.shipping_cost
          %tr
            %th 配送の方法
            %td
              = @product.shipping_method
          %tr
            %th 配送元地域
            %td
              = @product.source_area
          %tr
            %th 発送日の目安
            %td
              = @product.shipping_day
      .product-contents__price-box
        .product-contents__price-box--number
          .product-price
            ¥
            = @product.price
          .product-tax
            (税込)
          .product-shipping-fee
            送料込み
      - if current_user
        - if @product.buyer.nil? && @product.seller_id != current_user.id
          = link_to(purchase_path) do
            .product-contents__buy-button
              購入画面に進む
      - if @product.buyer.present?
        .product-contents__sold-button
          売り切れました
      .product-contents__description
        .product-contents__description--inner
          = @product.description
      .product-contents__left-button
        %button.product-contents__left-button--like
          %i.far.fa-heart いいね! ０
        %button.product-contents__left-button--report
          %i.far.fa-flag  不適切な商品の報告
      .product-contents__right-button
        = link_to "#" do
          %i.fas.fa-lock
          %span あんしん・あんぜんへの取り組み
    .product-messages
      %figure.user-image
        = image_tag("//static.mercdn.net/images/member_photo_noimage_thumb.png", class: "profile-image", width:"45px", height: "45px")
      .user-name
        ユーザーネーム
      .message-body
        .message-text
          こんばんは。
      .message-triangule
      %form.message-form
        #p.alert 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %p
        %textarea.comment{:cols => "100", :name => "comment", :rows => "10"}
        - if @product.buyer.present?
          %button.message-submit
            %span 売り切れのためコメントできません
        - if @product.buyer.nil?
          %button.message-submit
            %span コメントする
    .product-media
      = link_to "#" do
        .i.fab.fa-facebook-square.fa-3x.product-media__facebook
      = link_to "#" do
        .i.fab.fa-twitter-square.fa-3x.product-media__twitter
      = link_to "#" do
        .i.fab.fa-pinterest-square.fa-3x.product-media__pinterest
    .product-other-contents
      = link_to "#" do
        %h2 関連するカテゴリーその他の商品
      - @products.each do |product|
        - if product.id == @product.id
        - else
          .product-other-contents__box
            = link_to(product_path(product)) do
              %figure
                - if product.images.attached?
                  - product.images.each_with_index do |image, i|
                    - if i == 0
                      = image_tag image, class:"photo photo-#{i}"
            %h2
              = product.name
            .price-box
              ¥
              = product.price
            .price-box-tax (税込)
  = render 'layouts/aside'
  = render 'layouts/footer'